### ISSUE TITLE
Update docs to indicate how to use non-root context path.

### ISSUE THREAD

**Issue by metasim** [vmunier/scalajs-scripts#10]
The `play.http.context` value is set to something other than `/`, and when `@playscalajs.html.scripts` is expanded with the default assets mapper (which uses an absolute URI), you get 404s when loading the scripts.

I figured out that providing `fileName => routes.Assets.versioned(fileName).toString` as the second parameter fixes the problem, but it took quite a while to figure that out.

**Comment by vmunier** [comment]
The templates do not have default parameter values anymore, which forces to be explicit about all parameters and usage becomes less confusing.

As of scalajs-scripts `v1.0.0`, all the templates have the same parameters and are described in the README.md.
