### ISSUE TITLE
upgrade to twirl 1.3.0

### ISSUE THREAD

**Issue by antonkulaga** [vmunier/scalajs-scripts#12]
Please, upgrade to twirl 1.3.0 !

**Comment by danielnixon** [comment]
https://github.com/vmunier/scalajs-scripts/pull/13

**Comment by vmunier** [comment]
Fixed by https://github.com/vmunier/scalajs-scripts/commit/fab19c75f4b93242354ac87b7a44c7d0086870c0.

**Comment by vmunier** [comment]
Note that scalajs-scripts [`v1.1.0`](https://github.com/vmunier/scalajs-scripts/releases/tag/v1.1.0) has been published and it depends on Twirl `v1.3.0`.
