### ISSUE TITLE
Add option to add arbitrary attributes to the generated <script> tag

### ISSUE THREAD

**Issue by vpavkin** [vmunier/scalajs-scripts#16]
For example, it can be useful to add `defer/async` attribute to optimize page load time.

**Comment by vmunier** [comment]
Hi,

We could add an additional `htmlAttributes: Html` parameter with a default value, so that the new library version remains compatible with existing code.

Parameters of `src/main/twirl/scalajs/scripts.scala.html` would look like:
```
@(projectName:    String,
  assets:         String => String,
  resourceExists: String => Boolean
  resourceExists: String => Boolean,
  htmlAttributes: Html = Html("")
)
```

Usage would be:
```
@scalajs.html.scripts(
  projectName = "client",
  name => s"/assets/$name",
  name => getClass.getResource(s"/public/$name") != null,
  Html("defer async newAttr=newValue")
)
```

What do you think?

**Comment by vpavkin** [comment]
looks perfectly fine to me :) Sorry, haven't had time to make a pr yet :(

**Comment by vmunier** [comment]
No worries, I'll include the changes.
