### ISSUE TITLE
Change README language to be agnostic against templating language

### ISSUE THREAD

**Issue by mdedetrich** [vmunier/scalajs-scripts#18]
The README.md language of scalajs-scripts implies that its a helper for twirl however in reality it can be used with any scala templating language (such as scalatags which is actually how we use it).

In other words, scalajs-scripts is not specific to twirl since its pure Scala code that provides easy access to the compiled Scala-js js file. It works with twirl because you can (usually) just call Scala code in twirl, but the same applies to ScalaTags or any other HTML templating engine (or even just string interpolation).

I can go ahead and reword the README.md to reflect this if you agree?

**Comment by vmunier** [comment]
Hi,
Twirl can be used with scalatags (Twirl is not specific to Play framework by the way).
scalajs-scripts depends on Twirl and uses it: https://github.com/vmunier/scalajs-scripts/blob/fef81b18bf7e1a9b5cb380a5cff3d3f4ef664d73/build.sbt#L13
However, we could modify the README.md to make it clear that it can be used with ScalaTags and other libs.

**Comment by mdedetrich** [comment]
> However, we could modify the README.md to make it clear that it can be used with ScalaTags and other libs.

Yes this is the point. Not saying that scalajs-scripts can't be used with twirl, just that that it can be used with any HTML templating language.

Main point is that the language in README.md implied that scalajs-scripts is specifically designed/works with twirl

Should I make the a pr for the README.md to reflect this?

**Comment by vmunier** [comment]
A PR would be appreciated, thanks!

**Comment by mdedetrich** [comment]
@vmunier Done!
