### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by randm-ch** [vmunier/scalajs-scripts#21]
See PR #20
Thanks!

**Comment by vmunier** [comment]
The changes look good to me! Thank you for the Pull Request

**Comment by randm-ch** [comment]
@vmunier Glad I could help :) Can we expect a new version in the near future?

**Comment by vmunier** [comment]
@randm-ch scalajs-scripts `v1.1.3` has just been published to Maven Central.
