### ISSUE TITLE
implicit environment adds a lot of code

### ISSUE THREAD

**Issue by Whazor** [vmunier/scalajs-scripts#9]
I would say that this is not developer friendly, as you have to add this to every controller and view

**Comment by vmunier** [comment]
Hi @Whazor

As of Play 2.5, all the methods from the global `Play` object have been deprecated and `play.api.Environment` should be used instead https://github.com/playframework/playframework/blob/a3c81d286656f479d9bb4b9bfbd53cfe78bbea62/framework/src/play/src/main/scala/play/api/Play.scala#L202-L206.
The `resource` method is used by `jsdeps.scala.html`, `isProd` is used to know wether to include the `-fastopt.js` or `-opt.js` file.

A possible change:
We could drop the `implicit environment: Environment` parameter from the scripts, and add different boolean parameters that the user of the library should set. So `scripts.scala.html` would have the following parameters:
```
@(projectName: String,
  isProd: Boolean,
  includeJSDependencies: Boolean = true,
  assets:      String => String = fileName => s"/assets/$fileName",
  resources:   String => String = fileName => s"/public/$fileName"
)
```

You would still have to call `scripts.scala.html` using `environment: Environment` if you want the prod or dev files to be dynamically selected.
Example: `@playscalajs.html.scripts("client", isProd = environment.mode == play.api.Mode.Prod)`.

However, you would also have the option to set isProd explicitly if you do not want to bother passing the environment, as in: `@playscalajs.html.scripts("client", isProd = false)` when you are developing and changing to `@playscalajs.html.scripts("client", isProd = true)` for production!

**Comment by kzhouscala** [comment]
I agree with @Whazor. Requiring environment is a small change if you follow single page application design. Otherwise, you're left with changing many templates. How about adding a config property such as `scalajs.mode = prod` which can override existing configuration?

**Comment by kzhouscala** [comment]
It looks like DI in templates is WIP https://github.com/playframework/twirl/pull/100. To bypass environment, I went with using a custom scripts(..).

```scala
@defining("client") { projectName =>
    @playscalajs.html.jsdeps(projectName)
    @playscalajs.html.selectScript(projectName, isProd = ???)
    @playscalajs.html.launcher(projectName)
}
```

**Comment by vmunier** [comment]
Hi,

`play-scalajs-scripts` has been renamed to `scalajs-scripts` because the Play dependency was dropped. The usage of the library has changed, see the [README.md](https://github.com/vmunier/play-scalajs-scripts/blob/44278a3fa68a7d25d5a1bd80f7e9ad3171320dc5/README.md). You can try using the "new" library by adding: `"com.vmunier" %% "scalajs-scripts" % "1.0.0"`.

Code should be simpler for Play users as well, because the `Environment` is not required anymore.

Let me know if it helps.
